# Generated by Django 5.0.4 on 2024-08-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('http_method', models.CharField(max_length=15, verbose_name='HTTP method')),
                ('request_uri', models.CharField(max_length=255, verbose_name='Request URI')),
                ('response_code', models.PositiveSmallIntegerField(verbose_name='Response HTTP status code')),
                ('response_size', models.PositiveIntegerField(help_text='Size in bytes', verbose_name='Response size')),
                ('timestamp', models.DateTimeField(verbose_name='Request timestamp')),
            ],
            options={
                'verbose_name': 'Nginx log',
                'verbose_name_plural': 'Nginx logs',
            },
        ),
    ]
